# Generated by Django 6.0.2 on 2026-02-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
                ('img', models.ImageField(upload_to='partners/', verbose_name='Лого партнера')),
                ('link', models.CharField(help_text='Ссылка на их сайт или инстаграм или что-то', max_length=255, verbose_name='Ссылка на партнера')),
            ],
            options={
                'verbose_name': 'партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
