# Generated by Django 6.0.2 on 2026-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('small_text', models.TextField(verbose_name='Текст описание')),
                ('name_button', models.CharField(max_length=80, verbose_name='Название кнопки')),
                ('link_button', models.CharField(max_length=255, verbose_name='Ссылка кнопки')),
            ],
            options={
                'verbose_name': 'слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
