# Generated by Django 6.0.2 on 2026-02-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_img', models.ImageField(upload_to='about/', verbose_name='Большое фото')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('autograph_img', models.ImageField(upload_to='about/', verbose_name='фото подписи')),
            ],
            options={
                'verbose_name': 'о нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='BlogAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='about/', verbose_name='фото')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'блог компании',
                'verbose_name_plural': 'Блог компании',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'вопрос/ответ',
                'verbose_name_plural': 'Вопросы/Ответы',
            },
        ),
        migrations.CreateModel(
            name='PlusAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='about/', verbose_name='фото')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'плюс компании',
                'verbose_name_plural': 'Плюсы компании',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='about/', verbose_name='фото')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='должность')),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
