# Generated by Django 6.0.2 on 2026-03-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plusabout',
            options={'ordering': ['-id'], 'verbose_name': 'плюс компании', 'verbose_name_plural': 'Плюсы компании'},
        ),
    ]
