# Generated by Django 6.0.2 on 2026-04-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_plusabout_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_site', models.CharField(max_length=150, verbose_name='Название сайта')),
                ('description_site', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание сайта')),
                ('keywords_site', models.TextField()),
                ('phone_main', models.CharField(max_length=18, verbose_name='Телефон №1')),
                ('phone_second', models.CharField(blank=True, max_length=18, null=True, verbose_name='Телефон №2')),
                ('text_small_homepage_1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Мини заголовок')),
                ('text_homepage_1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Заголовок')),
                ('text_small_1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Под заголовок')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на facebook')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на telegram')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на twitter')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на instagram')),
                ('tiktok', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на tiktok')),
                ('youtube', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на youtube')),
                ('vk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на vk')),
                ('ok', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на odnoklassniki')),
            ],
            options={
                'verbose_name': 'настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
