# Generated by Django 6.0.2 on 2026-03-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(help_text='iframe вставляем из источников', max_length=255, verbose_name='Карта')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
