# Generated by Django 6.0.2 on 2026-03-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='map',
            field=models.TextField(help_text='iframe вставляем из источников', verbose_name='Карта'),
        ),
    ]
